### PR TITLE
Include mozilla css, minus Polish translation

### PR DESCRIPTION
**Pull request by limed**
Our mozilla mailman instance has some templates and css associated with it, this PR will help include the templates, minus the Polish translation.

### CODE REVIEW

**Comment by splewako** [comment]
I will be happy to integrate all Mozilla specific changes but in the same time I would like to keep master clean for easier upstream updating.

Would Mozilla specific branch per version (ie mozilla-2.1.18, mozilla-2.1.19, mozilla-2.1.20) would work? This way it would be easy to include future Mozilla specific customizations. Would tags (ie 2.1.18-mozilla, 2.1.19-mozilla, 2.1.20-mozilla) on these branches be useful?

**Comment by splewako** [comment]
BTW: Can I translate added texts after merging?

**Comment by limed** [comment]
I'm ok with keeping a separate branch for this, and yes its ok to translate text after merging, I'll just grab the files again. I'm wondering if the utf-8 changes can be pushed upstream?

**Comment by splewako** [comment]
OK, I created [mozilla-2.1.18](https://github.com/aviarypl/mailman-l10n-pl/commits/mozilla-2.1.18), [mozilla-2.1.19](https://github.com/aviarypl/mailman-l10n-pl/commits/mozilla-2.1.19) and [mozilla-2.1.20](https://github.com/aviarypl/mailman-l10n-pl/commits/mozilla-2.1.20) branches and added 2.1.18-mozilla, 2.1.19-mozilla, 2.1.20-mozilla [tags](https://github.com/aviarypl/mailman-l10n-pl/releases).

> I'm wondering if the utf-8 changes can be pushed upstream?

No, sadly. :(
I attempted that but Mark Sapiro was concerned about string valued attributes in existing lists configurations.

**Pull request closed without merging**
